### ISSUE TITLE
Order of components in `explMembers` matters

### ISSUE THREAD

**Issue by MagicRB** [jonascarpay/apecs#127]
I have not seen this documented anywhere, so I'm opening this as a _"let's close immediately but someone might find it useful anyway"_ or _"let's add a note to the docs"_. 

Given two components `PositionComponent` and `BoxComponent` and 5000 entities with only `PositionComponent`s, a query such as the one below will run at full speed:

```haskell
cmap @(BoxComponent, PositionComponent) ....
```

while this one is depend on the number of `PositionComponent`s in the world

```haskell
cmap @(PositionComponent, BoxComponent)
```

This behavior makes sense when one looks at how `explMembers` is implemented for tuples, I wonder if there is a more efficient implementation. Perhaps a store wrapper around components which could also notify aggregate component stores of changes? Kind of like archetypes which only do anything for `explMembers` to speed it up while just delegating to the backing stores for the rest of `expl...`

My current recommendation is to order components from _"least likely"_ to _"most likely"_

**Comment by MagicRB** [comment]
What could be done, is having the tuple instance first ask for the number of components in each store, (my own `SparseSet` store can do this in `O(1)` as can most others I assume) and then start from the smallest number of matching components, removing the need for manual guess-work sorting.

**Comment by jship** [comment]
> I have not seen this documented anywhere

It's documented in the [tutorial](https://github.com/jonascarpay/apecs/blob/master/examples/Shmup.md), though it could potentially be easy to gloss over the performance ramifications since they're a tad implicit:

> > When we iterate over a tuple, what happens internally is that we iterate over all Entities that have the first Component (Position), and then test whether the Entity also has the remaining Components, in this case Velocity.

It's also documented in more detail in the section `III.E Composition` of the library's [paper](https://github.com/jonascarpay/apecs/blob/master/apecs/prepub.pdf), but I think we could improve the library Haddocks either on the tuple instances or the `cmap` functions (or both) so that users wouldn't need to have read the paper or studied the source to get the most performance out of the library.

> My current recommendation is to order components from "least likely" to "most likely"

That's a good rule of thumb, but with the current implementation, you can simplify this by ensuring the "least likely" component is first and not ordering the rest. The remaining components can be in any order, as each one is retrieved directly for the entity that has the first component.

**Comment by MagicRB** [comment]
Fair, I didn't look the tutorial originally just at the haddocks, they're a bit more digestible for me. I figured out what's happening by analyzing the TH code.

**Comment by jonascarpay** [comment]
Agreed that having the explanation repeated in the haddocks would be nice.

> What could be done, is having the tuple instance first ask for the number of components in each store, (my own SparseSet store can do this in O(1) as can most others I assume) and then start from the smallest number of matching components, removing the need for manual guess-work sorting.

This would be nice, and something that I've considered adding a number of times. Unfortunately, it's a bit more complicated to implement than you might expect, and not necessarily always a good idea. For example
- not every store knows how many things it contains (e.g. `NotStore` has infinite elements)
- the ideal traversal order is not necessarily always from smallest to largest, but the order that eliminates most entities, fastest
- people who don't want to use it would pay for the overhead
- it's currently possible to implement as an extension yourself

Since apecs is essentially an in-memory database, there's a lot of pressure to do more database-y things like (in this case) query optimization. However, I think apecs is in a pretty good place feature/design-wise, where it's nice and transparent, and easy to reason about. I think it'd be a fun exercise to add a sqlite backend though, and get "proper" query optimization (:

**Comment by MagicRB** [comment]
> This would be nice, and something that I've considered adding a number of times. Unfortunately, it's a bit more complicated to implement than you might expect, and not necessarily always a good idea. For example

Ok, that's fair, I may try to make something myself inside my project.

> Since apecs is essentially an in-memory database, there's a lot of pressure to do more database-y things like (in this case) query optimization. However, I think apecs is in a pretty good place feature/design-wise, where it's nice and transparent, and easy to reason about. I think it'd be a fun exercise to add a sqlite backend though, and get "proper" query optimization (:

If I get stuck implementing a PosgreSQL backend, you're to blame :)

**Comment by jship** [comment]
Added a docs PR here for this issue here: #130
