### ISSUE TITLE
How to destroy all components of entity.

### ISSUE THREAD

**Issue by robinp** [jonascarpay/apecs#13]
Assuming I want to get rid of the entity completely (say a decal went out of screen), how would I do it? AFAIU `destroy` just removes a given component.

**Comment by jonascarpay** [comment]
You can't destroy an entity, you can only destroy each of its components. An `Entity` is just an integer that may or may not some components associated with it.
`newEntity` is a convenience function, instead of
```haskell
do newEntity (Position 1)
   newEntity (Position 2)
```
you could write
```haskell
do set 0  (Position 1)
   set 1  (Position 2)
```
but `newEntity` uses the global `EntityCounter` so you don't have to count yourself.

You can destroy multiple components at once with `destroy (undefined :: (c1, c2, ...)) ety`.
For multiple entities, use `cmap $ \(_ :: c1) -> Nothing :: Maybe c2`, where you can also use tuples to destroy multiple components.

There is currently no way to destroy all components for a given entity. I might add some support for this in the future, but if you use type synonyms for common tuples, it shouldn't be an issue. Does that answer your question?

**Comment by robinp** [comment]
Well, that means the client would have to keep track of which entity having which component.

For example, the condition to destroy something can be as simple as getting out of screen, needing only the `Position` component. But then practically random components can be present, not all entities need to have the same ones (also, even the same kind of entities can have some components present dynamically).

Maintaining this mapping internally in `Apecs` sounds like a good idea - but maybe gather feedback from other users too before actioning based on my perspective.

**Comment by tejon** [comment]
It seems like it should be possible to make a component of the list of other components on an entity, perhaps using something like [`EADT/Variant`](http://hsyl20.fr/home/posts/2018-05-22-extensible-adt.html), which could then be batch-killed. This seems like a distinctly more complex problem than the core ECS architecture, though. It would need a whole layer of machinery to make sure every component is registered.

If this can be done without impacting complexity or versatility of the API, or the performance of Apecs, well, great! ...but there's a good chance it should be a dependent package, not part of the core system; and that's probably the best way to start prototyping in any case.

**Comment by jonascarpay** [comment]
The easiest way to destroy out-of-bounds entities right now is probably to do
```haskell
cmapM_ $ \(Position p, ety) -> when (outOfBounds p) (destroyAll ety)
```
with
```haskell
destroyAll = destroy (undefined :: (c1, c2, ..))
```
where the list c1,c2.. is just a tuple of all components. If you have too many to fit into the default tuples you can do ((c1,c2,c3..),(c4,c5,c6..)). Attempting to delete a component that isn't there is not a problem.

I am working on a new version with a different type class structure that allows you to easily say things like "when this component gets deleted also delete these components". The new version would make something like @tejon's idea a lot easier as well, having components in separate stores interact is currently pretty hacky.

**Comment by robinp** [comment]
@jonascarpay good enough on first approximation, thank you.

**Comment by jonascarpay** [comment]
Yes, a global ignores its entity arguments, which is useful if you want to set/get it from a cmap. Destroying/iterating over a global will be a type error in the next update, however. I'm closing this issue, let me know if you run into anything else.
