### ISSUE TITLE
The use of Monoid for Global values is a bit strange

### ISSUE THREAD

**Issue by AnthonySuper** [jonascarpay/apecs#26]
Currently, apecs uses the `mempty` member of `Monoid` to provide a default for global values. This makes sense initially: it's the standard Haskell way to represent the "default" value of something.

However, problems come when we start defining other global components. I often have global components which do not sensibly fit the `Semigroup` or `Monoid` laws. For example, given something like this:

```haskell
newtype Score = Score { getScore :: Int }
```

There's really no sensible way for me to "monoidally combine" scores, because they're not intended to have that kind of structure. I could always leave the instances blank except for `mempty`, or write rule-breaking instances, but that might be surprising to other users.

As such, I propose a new typeclass:

```haskell

class ApecsGlobal a where
    apecsDefault :: a
```

We could then use `apecsDefault` instead of `mempty` where needed. We could even define this:

```haskell
instance (Monoid a) => ApecsGlobal a where
    apecsDefault = mempty
``` 

This would provide backwards-compatibility.

**Comment by jonascarpay** [comment]
I see your issue. However, I'd argue that the problem isn't that globals aren't monoids, the problem is a failure to communicate that most _are_.
In the case of `Score` for example, you start at 0 and you mostly just add to it, that's a `Sum` monoid, as is something like `Time`. The `Camera` in `apecs-gloss` has a position and a scale, its `mappend` is additive in the position and multiplicative in scale.
Still, i definitely see the issue. Not _all_ globals are monoids, and the examples/documentation definitely don't hint at the fact that most are. For example, `Score` and `Time` in `shmup` have incomplete `Monoid` instances, which is poor form. They should both be `newtype`s around `Sum`, and then we just derive the necessary instances. Also, I think the API is sorely lacking something like `mappendGlobal` (`gmappend`?), since so many operations on globals are really just `mappend`.

**Comment by AnthonySuper** [comment]
I do see the point there! I'm trying to think of a global that *wouldn't* be a `Monoid` and I really can't think of any. I was going to say some sort of file cache, but that would probably wind up being a `Map Text Bytestring` internally, and that has a `monoid` instance defined. Maybe some sort of input configuration?

```

data GameControls = GameControls { jumpButton :: Key, attackButton :: Key }

```

This is hard to define a (rule-abiding) `Monoid` instance for.

**Comment by jonascarpay** [comment]
Even for those, there are trivial instances like `Last` that correspond reasonably well to what you are doing, but in cases like that it should be fine to have an unlawful monoid instance/just leave `mappend` undefined. The issue with things like [data-default](https://hackage.haskell.org/package/data-default) is that the only time it's not ambiguous what the default value is, is when there is a monoid instance. This is less of a problem when you're supplying the values yourself, but it's not good for extensibility. I'm leaving this issue open until the API properly nudges people toward useful monoid instances though.
