### ISSUE TITLE
Performance mystery

### ISSUE THREAD

**Issue by jonascarpay** [jonascarpay/apecs#7]
For some reason the definition of `Unique`'s `explMembers` has a significant effect on the benchmark results. This is weird, because the benchmark does not use `Unique` at all.

If anyone has a clue as to why this could happen, please let me know.

---
These definitions are fast:
```haskell
explMembers (Unique eref _) = U.singleton <$> readIORef eref -- old, unsafe dfn
explMembers (Unique eref _) = f <$> readIORef eref
  where f (-1) = mempty
        f x    = U.singleton x
```
```
benchmarking ecs_bench/init: 283.5 μs   (281.4 μs .. 285.9 μs)
benchmarking ecs_bench/step: 330.4 μs   (328.2 μs .. 333.7 μs)
```
---
This one's slow:
```haskell
explMembers (Unique eref _) = do
  e <- readIORef eref
  return $ if e == -1 then mempty else U.singleton e
```
```
benchmarking ecs_bench/init: 329.1 μs   (323.0 μs .. 335.6 μs)
benchmarking ecs_bench/step: 372.0 μs   (368.5 μs .. 375.7 μs)
```

**Comment by boj** [comment]
@jonascarpay Were you able to figure anything out?

Running the standard benchmarks in `master` under GHC 8.0.2 showed no discernible difference in benchmark speeds when changing the relevant lines to your slow version, however, I wasn't seeing a `ecs_bench` result so maybe I am not staring at the same thing?

An offhand uneducated guess without doing any profiling is that doing the computation in a monad instead of applicative may incur some allocation cost because of the intermediate `e` value?

**Comment by jonascarpay** [comment]
Thanks for testing. It seems like be032fd somehow fixed it. I tried, and it wasn't changing the criterion config that fixed it.
That leaves changing `mod` to `rem`, which increased performance altogether but evidently also made it immune to changing some unrelated definition.

I guess I should close the issue, but I'm still very curious as to what could have caused this.
