### ISSUE TITLE
Question about `nextEntity` and concurrency

### ISSUE THREAD

**Issue by thalesmg** [jonascarpay/apecs#73]
First of all, thanks for all your work on this awesom library! 🍻

Does the library support concurrency? As I understand, it'd seem so, since it uses `IORef` as the `IO` storage. But the [current `nextEntity`](https://github.com/jonascarpay/apecs/blob/ce43e3e00dc5b80db69c1f4179f72933bc3d0a9e/apecs/src/Apecs/Util.hs#L44-L45) seems to be susceptible to race conditions:

```haskell
nextEntity :: (MonadIO m, Get w m EntityCounter) => SystemT w m Entity
nextEntity = do EntityCounter n <- get global
                setReadOnly global (EntityCounter $ n+1)
                return (Entity . getSum $ n)
```

If two or more threads concurrently call `nextEntity`, there is a chance that two or more of them will get the same `Entity` value.

Is my understanding correct? Or is there something that prevents this situation from occuring?

Cheers!

**Comment by jonascarpay** [comment]
Your understanding is correct, the base library does not provide any protection against race conditions. Instead, support for concurrency is handled by [apecs-stm](https://hackage.haskell.org/package/apecs-stm).

Using it is simple; just use the `Apecs.STM.Prelude` module instead of the regular `Apecs` module. It exports STM-compatible versions of the normal apecs prelude plus a few STM-related functions. In short, `forkSys` runs a system on a new thread, and `atomically` then runs a system atomically.

**Comment by thalesmg** [comment]
Awesome! Thanks for the fast answer.
I thought of using a variant of `nextEntity` that uses `atomicModifyIORef`, but using `apecs-stm` seems simpler. =)
